const productList = [
  {
    key: 1,
    id: 1,
    name: "Tuna - Yellowfin",
    tags: ["FAST_SHIPPING", "FREE_SHIPPING"],
    img: "http://dummyimage.com/145x100.png/cc0000/ffffff",
    url: "https://shoppingcart.com/product/1",
    quantity: 558,
    price: 19,
    onlineStatus: false,
    physicalStatus: true,
    productNumber: "PN001",
  },
  {
    key: 2,
    id: 2,
    name: "Chicken - Livers",
    tags: ["MEMBER_EXCLUSIVE", "FREE_SHIPPING"],
    img: "http://dummyimage.com/216x100.png/5fa2dd/ffffff",
    url: "https://shoppingcart.com/product/2",
    quantity: 15,
    price: 397,
    onlineStatus: true,
    physicalStatus: true,
    productNumber: "PN002",
  },
  {
    key: 3,
    id: 3,
    name: "Appetizer - Smoked Salmon / Dill",
    tags: ["FAST_SHIPPING", "BEST_SELLER"],
    img: "http://dummyimage.com/196x100.png/ff4444/ffffff",
    url: "https://shoppingcart.com/product/3",
    quantity: 220,
    price: 207,
    onlineStatus: true,
    physicalStatus: false,
    productNumber: "PN003",
  },
  {
    key: 4,
    id: 4,
    name: "Yoghurt Tubes",
    tags: ["FREE_SHIPPING"],
    img: "http://dummyimage.com/196x100.png/5fa2dd/ffffff",
    url: "https://shoppingcart.com/product/4",
    quantity: 71,
    price: 621,
    onlineStatus: false,
    physicalStatus: false,
    productNumber: "PN004",
  },
  {
    key: 5,
    id: 5,
    name: "Thyme - Dried",
    tags: ["DISCOUNT", "BEST_SELLER"],
    img: "http://dummyimage.com/111x100.png/5fa2dd/ffffff",
    url: "https://shoppingcart.com/product/5",
    quantity: 696,
    price: 658,
    onlineStatus: true,
    physicalStatus: true,
    productNumber: "PN005",
  },
  {
    key: 6,
    id: 6,
    name: "Beef - Sushi Flat Iron Steak",
    tags: ["MEMBER_EXCLUSIVE"],
    img: "http://dummyimage.com/101x100.png/dddddd/000000",
    url: "https://shoppingcart.com/product/6",
    quantity: 198,
    price: 363,
    onlineStatus: false,
    physicalStatus: true,
    productNumber: "PN006",
  },
  {
    key: 7,
    id: 7,
    name: "Pastry - Apple Muffins - Mini",
    tags: ["FAST_SHIPPING"],
    img: "http://dummyimage.com/103x100.png/cc0000/ffffff",
    url: "https://shoppingcart.com/product/7",
    quantity: 511,
    price: 991,
    onlineStatus: false,
    physicalStatus: false,
    productNumber: "PN007",
  },
  {
    key: 8,
    id: 8,
    name: "Rambutan",
    tags: ["FAST_SHIPPING", "DISCOUNT"],
    img: "http://dummyimage.com/184x100.png/dddddd/000000",
    url: "https://shoppingcart.com/product/8",
    quantity: 84,
    price: 827,
    onlineStatus: true,
    physicalStatus: false,
    productNumber: "PN008",
  },
  {
    key: 9,
    id: 9,
    name: "Wine - Soave Folonari",
    tags: ["DISCOUNT", "FREE_SHIPPING"],
    img: "http://dummyimage.com/134x100.png/dddddd/000000",
    url: "https://shoppingcart.com/product/9",
    quantity: 646,
    price: 976,
    onlineStatus: false,
    physicalStatus: true,
    productNumber: "PN009",
  },
  {
    key: 10,
    id: 10,
    name: "Jam - Apricot",
    tags: ["FREE_SHIPPING", "MEMBER_EXCLUSIVE"],
    img: "http://dummyimage.com/135x100.png/ff4444/ffffff",
    url: "https://shoppingcart.com/product/10",
    quantity: 735,
    price: 871,
    onlineStatus: true,
    physicalStatus: true,
    productNumber: "PN010",
  },
];

export default productList;
